### ISSUE TITLE
Tests reported as passing eroneously when a top-level error occurs

### ISSUE THREAD

**Issue by dbp** [racket/htdp#212]
Running this:

```
#lang htdp/isl+

(define (badfn x)
  (error "hello"))

(check-expect (badfn 1) 1)

(error "hello")
```

Produces:

<img width="243" alt="Screenshot 2023-11-29 at 9 05 27 AM" src="https://github.com/racket/htdp/assets/569509/a96fc9b9-80b5-4174-9d6b-dba12ea96352">

In the non-#lang it's better; while the interactions window still prints the buggy "The test passed", a window pops up with the correctly failing test.

Interactions window:
<img width="211" alt="Screenshot 2023-11-29 at 9 06 13 AM" src="https://github.com/racket/htdp/assets/569509/9249e949-cfba-449a-a16c-938c4d8abf69">

Pop up:
<img width="746" alt="Screenshot 2023-11-29 at 9 06 36 AM" src="https://github.com/racket/htdp/assets/569509/13c2c3e4-2dfc-4e29-8350-02dfaf942335">

**Comment by samth** [comment]
Which version is this? A similar bug #203 was fixed recently.

**Comment by rfindler** [comment]
I suspect it is fixed but, just in case it wasn't obvious and you want to try it out yourself, if you have your two version installations in separate directories, then you should be able to have both of them on your machine (this works especially well for me on mac os with multiple folders in /Applications plus a couple of git checkouts elsewhere for development, even).

**Comment by mfelleisen** [comment]
It is fixed. I double-checked.

**Comment by shhyou** [comment]
I'm on racket/htdp#42f0782 (“stepper history no update for 8.11”) and racket/drracket#6257cb8 (“when receiving syntax objects from 'online-check-syntax logger”).

I still see the message "The test passed!" in `#lang htdp/isl+` and Intermediate Student with lambda, although the test didn't pass. Am I missing anything?

**Comment by shhyou** [comment]
@dbp I didn't see the pop-up test engine window in your screenshot (could be due to version differences).

**Comment by dbp** [comment]
So, to confirm, this definitely seems like an issue in the released 8.11 (I see identical behavior, Apple Silicon build). And it seems like the #203 fixes were included in that?

**Comment by mfelleisen** [comment]
Oops .. I ran this in the menu based languages and didn't pay attention. So sorry.

**Comment by rfindler** [comment]
It looks like this example used to work, in version 8.9.

**Comment by mikesperber** [comment]
"Works" is relative, as two bugs cancelled each other out, and one of them got fixed with #203. I'm looking into this one.

**Comment by mikesperber** [comment]
@rfindler @dbp @mfelleisen @shhyou I see what's happening, but I need some guidance as to what the behavior should be / what the mental model here is supposed to be:

My mental model has been that the tests get run after the "regular" program has run, and that exceptions in the regular program stop execution.

In the program here, the "regular" program bombs - and the tests therefore don't get run. If that's basically what we want, it's just the message that's wrong, and I have a fix ready. 

If we want the tests to run always - even if the main program fails - we need a different fix. (This was basically that 8.10 did, and I assumed that was wrong.)

**Comment by rfindler** [comment]
Your mental model matches what mine is.

Robby

**Comment by mfelleisen** [comment]
Exactly.

**Comment by mikesperber** [comment]
Thanks - just pushed #213 to fix this.

**Comment by rfindler** [comment]
Matthias posted a follow up to the commit that closed this issue with this program:

```
(check-expect (g 30) "goodbye")
(f 40)
(define (f x) "hello")
(define (g y) "goodbye")
```

which, when I run it in the language-menu based version of BSL, I see:

```
Welcome to DrRacket, version 8.11.1.5--2023-12-11(0b2a5d97/d) [cs].
Language: Beginning Student; memory limit: 256 MB.
The test passed!f is used here before its definition
> 
```

**Comment by shhyou** [comment]
I just updated `htdp-lib` and see `0 tests passed.f is used here before its definition`.

**Comment by rfindler** [comment]
Oh, I see that too now. I wonder if I used the wrong DrRacket in my tests (as I have updated only one of them so far).
